version: "3.3"
services:
  web:
    build: .
    image: socialbackend/django
    command: 'python manage.py makemigrations && python manage.py migrate &&python manage.py runserver -a 0.0.0.0:8080'
    ports:
      - "8080:8080"
    

